name: Bump version
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  newrelic:
    needs: build
    runs-on: ubuntu-latest
    name: New Relic
    steps:
    # This step builds a var with the release tag value to use later
    - name: Set Release Version from Tag
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
    # This step creates a new Change Tracking Marker
    - name: New Relic Application Deployment Marker
      uses: newrelic/deployment-marker-action@v2.3.0
      with:
        apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
        guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
        version: "${{ env.RELEASE_VERSION }}"
        user: "${{ github.actor }}"
        description: ${{ github.event.head_commit.message }}
